/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Julython API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CallbackAuthCallbackGetParams,
  HTTPValidationError,
  SessionData
} from '../endpoints.schemas';





/**
 * @summary Login
 */
export const loginAuthLoginProviderGet = (
    provider: 'github' | 'gitlab', options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {


    return axios.default.get(
      `/auth/login/${provider}`,options
    );
  }




export const getLoginAuthLoginProviderGetQueryKey = (provider?: 'github' | 'gitlab',) => {
    return [
    `/auth/login/${provider}`
    ] as const;
    }


export const getLoginAuthLoginProviderGetQueryOptions = <TData = Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError = AxiosError<HTTPValidationError>>(provider: 'github' | 'gitlab', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginAuthLoginProviderGetQueryKey(provider);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>> = ({ signal }) => loginAuthLoginProviderGet(provider, { signal, ...axiosOptions });





   return  { queryKey, queryFn, enabled: !!(provider), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LoginAuthLoginProviderGetQueryResult = NonNullable<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>>
export type LoginAuthLoginProviderGetQueryError = AxiosError<HTTPValidationError>


export function useLoginAuthLoginProviderGet<TData = Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError = AxiosError<HTTPValidationError>>(
 provider: 'github' | 'gitlab', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginAuthLoginProviderGet>>,
          TError,
          Awaited<ReturnType<typeof loginAuthLoginProviderGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginAuthLoginProviderGet<TData = Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError = AxiosError<HTTPValidationError>>(
 provider: 'github' | 'gitlab', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginAuthLoginProviderGet>>,
          TError,
          Awaited<ReturnType<typeof loginAuthLoginProviderGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginAuthLoginProviderGet<TData = Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError = AxiosError<HTTPValidationError>>(
 provider: 'github' | 'gitlab', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Login
 */

export function useLoginAuthLoginProviderGet<TData = Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError = AxiosError<HTTPValidationError>>(
 provider: 'github' | 'gitlab', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginAuthLoginProviderGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoginAuthLoginProviderGetQueryOptions(provider,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Callback
 */
export const callbackAuthCallbackGet = (
    params: CallbackAuthCallbackGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {


    return axios.default.get(
      `/auth/callback`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getCallbackAuthCallbackGetQueryKey = (params?: CallbackAuthCallbackGetParams,) => {
    return [
    `/auth/callback`, ...(params ? [params]: [])
    ] as const;
    }


export const getCallbackAuthCallbackGetQueryOptions = <TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = AxiosError<HTTPValidationError>>(params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCallbackAuthCallbackGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof callbackAuthCallbackGet>>> = ({ signal }) => callbackAuthCallbackGet(params, { signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CallbackAuthCallbackGetQueryResult = NonNullable<Awaited<ReturnType<typeof callbackAuthCallbackGet>>>
export type CallbackAuthCallbackGetQueryError = AxiosError<HTTPValidationError>


export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = AxiosError<HTTPValidationError>>(
 params: CallbackAuthCallbackGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = AxiosError<HTTPValidationError>>(
 params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof callbackAuthCallbackGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = AxiosError<HTTPValidationError>>(
 params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Callback
 */

export function useCallbackAuthCallbackGet<TData = Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError = AxiosError<HTTPValidationError>>(
 params: CallbackAuthCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof callbackAuthCallbackGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCallbackAuthCallbackGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get User Session
 */
export const getUserSessionAuthSessionGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SessionData>> => {


    return axios.default.get(
      `/auth/session`,options
    );
  }




export const getGetUserSessionAuthSessionGetQueryKey = () => {
    return [
    `/auth/session`
    ] as const;
    }


export const getGetUserSessionAuthSessionGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError = AxiosError<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserSessionAuthSessionGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>> = ({ signal }) => getUserSessionAuthSessionGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserSessionAuthSessionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>>
export type GetUserSessionAuthSessionGetQueryError = AxiosError<void>


export function useGetUserSessionAuthSessionGet<TData = Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError = AxiosError<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>,
          TError,
          Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSessionAuthSessionGet<TData = Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>,
          TError,
          Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserSessionAuthSessionGet<TData = Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Session
 */

export function useGetUserSessionAuthSessionGet<TData = Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError = AxiosError<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserSessionAuthSessionGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserSessionAuthSessionGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Logout
 */
export const logoutAuthLogoutGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {


    return axios.default.get(
      `/auth/logout`,options
    );
  }




export const getLogoutAuthLogoutGetQueryKey = () => {
    return [
    `/auth/logout`
    ] as const;
    }


export const getLogoutAuthLogoutGetQueryOptions = <TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutAuthLogoutGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof logoutAuthLogoutGet>>> = ({ signal }) => logoutAuthLogoutGet({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LogoutAuthLogoutGetQueryResult = NonNullable<Awaited<ReturnType<typeof logoutAuthLogoutGet>>>
export type LogoutAuthLogoutGetQueryError = AxiosError<unknown>


export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>,
          TError,
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>,
          TError,
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Logout
 */

export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLogoutAuthLogoutGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




