application: julython
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DJANGO_SETTINGS_MODULE: 'july.settings'

builtins:
- appstats: on
- remote_api: on
- admin_redirect: on
- django_wsgi: on
- deferred: on

inbound_services:
- warmup

libraries:
- name: django
  version: "1.3"

handlers:
- url: /static
  static_dir: july/static_root

- url: /(favicon.ico|robots.txt)
  static_files: july/static_root/\1
  upload: /static/(.*)

- url: /api.*
  script: july.api.app
  