from datetime import datetime


class User:
    id = "aaaaaaaaa-bbbb-cccc-dddd-eeeeeeeee"
    email = "jimmy@julython.org"
    name = "Jimmy Johnson"


INAUGURAL_GAME = datetime(year=2012, month=7, day=4)
INAUGARAL_TIME = int(INAUGURAL_GAME.timestamp())

GITHUB_PAYLOAD = {
    "ref": "refs/heads/master",
    "before": "bde5f4701a62ff706d6c0093350006509d53df20",
    "after": "50dd4db9fe7c7cd3c366044ca273f028d1457d90",
    "repository": {
        "id": 3977964,
        "node_id": "MDEwOlJlcG9zaXRvcnkzOTc3OTY0",
        "name": "appengine-debugtoolbar",
        "full_name": "rmyers/appengine-debugtoolbar",
        "private": False,
        "owner": {
            "name": "rmyers",
            "email": "rmyers@anaconda.com",
            "login": "rmyers",
            "id": 518026,
            "node_id": "MDQ6VXNlcjUxODAyNg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/518026?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/rmyers",
            "html_url": "https://github.com/rmyers",
            "type": "User",
            "user_view_type": "public",
            "site_admin": False,
        },
        "html_url": "https://github.com/rmyers/appengine-debugtoolbar",
        "description": "Debug toolbar for simple wsgi apps on Appengine",
        "fork": False,
        "url": "https://api.github.com/repos/rmyers/appengine-debugtoolbar",
        "forks_url": "https://api.github.com/repos/rmyers/appengine-debugtoolbar/forks",
        "created_at": 1334023345,
        "updated_at": INAUGURAL_GAME.isoformat(),
        "pushed_at": INAUGARAL_TIME,
        "git_url": "git://github.com/rmyers/appengine-debugtoolbar.git",
        "ssh_url": "git@github.com:rmyers/appengine-debugtoolbar.git",
        "clone_url": "https://github.com/rmyers/appengine-debugtoolbar.git",
        "svn_url": "https://github.com/rmyers/appengine-debugtoolbar",
        "homepage": "",
        "size": 236,
        "stargazers_count": 2,
        "watchers_count": 2,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "has_discussions": False,
        "forks_count": 0,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 0,
        "license": None,
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 2,
        "default_branch": "master",
        "stargazers": 2,
        "master_branch": "master",
    },
    "pusher": {"name": "rmyers", "email": "rmyers@anaconda.com"},
    "sender": {
        "login": "rmyers",
        "id": 518026,
        "node_id": "MDQ6VXNlcjUxODAyNg==",
        "avatar_url": "https://avatars.githubusercontent.com/u/518026?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rmyers",
        "html_url": "https://github.com/rmyers",
        "type": "User",
        "user_view_type": "public",
        "site_admin": False,
    },
    "created": False,
    "deleted": False,
    "forced": True,
    "base_ref": None,
    "compare": "https://github.com/rmyers/appengine-debugtoolbar/compare/bde5f4701a62...50dd4db9fe7c",
    "commits": [
        {
            "id": "50dd4db9fe7c7cd3c366044ca273f028d1457d90",
            "tree_id": "711940618ce80d0b260e10d270fbc7305747066a",
            "distinct": True,
            "message": "touching the readme against me",
            "timestamp": "2025-12-07T14:20:24-06:00",
            "url": "https://github.com/rmyers/appengine-debugtoolbar/commit/50dd4db9fe7c7cd3c366044ca273f028d1457d90",
            "author": {
                "name": "Robert Myers",
                "email": "rmyers@anaconda.com",
                "date": "2025-12-07T14:18:47-06:00",
                "username": "rmyers",
            },
            "committer": {
                "name": "Robert Myers",
                "email": "rmyers@anaconda.com",
                "date": "2025-12-07T14:20:24-06:00",
                "username": "rmyers",
            },
            "added": [],
            "removed": [],
            "modified": ["README.rst"],
        }
    ],
    "head_commit": {
        "id": "50dd4db9fe7c7cd3c366044ca273f028d1457d90",
        "tree_id": "711940618ce80d0b260e10d270fbc7305747066a",
        "distinct": True,
        "message": "touching the readme against me",
        "timestamp": "2025-12-07T14:20:24-06:00",
        "url": "https://github.com/rmyers/appengine-debugtoolbar/commit/50dd4db9fe7c7cd3c366044ca273f028d1457d90",
        "author": {
            "name": "Robert Myers",
            "email": "rmyers@anaconda.com",
            "date": "2025-12-07T14:18:47-06:00",
            "username": "rmyers",
        },
        "committer": {
            "name": "Robert Myers",
            "email": "rmyers@anaconda.com",
            "date": "2025-12-07T14:20:24-06:00",
            "username": "rmyers",
        },
        "added": [],
        "removed": [],
        "modified": ["README.rst"],
    },
}
