ALTER TABLE users ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE users ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE user_identifiers ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE user_identifiers ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE games ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE games ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE projects ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE projects ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE commits ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE commits ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE players ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE players ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE boards ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE boards ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE languages ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE languages ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE language_boards ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE language_boards ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE teams ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE teams ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE team_members ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE team_members ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE team_boards ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE team_boards ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE reports ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE reports ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE audit_logs ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE audit_logs ALTER COLUMN updated_at DROP DEFAULT;