/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Julython API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GitHubWebhook,
  HTTPValidationError,
  ListReposApiGithubReposGetParams,
  RepoListResponse
} from '../endpoints.schemas';





/**
 * List GitHub repositories the user can manage webhooks for.

Query params:
    include_webhooks: If true, fetch existing webhooks for each repo (slower)
 * @summary List Repos
 */
export const listReposApiGithubReposGet = (
    params?: ListReposApiGithubReposGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RepoListResponse>> => {
    
    
    return axios.default.get(
      `/api/github/repos`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getListReposApiGithubReposGetQueryKey = (params?: ListReposApiGithubReposGetParams,) => {
    return [
    `/api/github/repos`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListReposApiGithubReposGetQueryOptions = <TData = Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError = AxiosError<HTTPValidationError>>(params?: ListReposApiGithubReposGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReposApiGithubReposGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReposApiGithubReposGet>>> = ({ signal }) => listReposApiGithubReposGet(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListReposApiGithubReposGetQueryResult = NonNullable<Awaited<ReturnType<typeof listReposApiGithubReposGet>>>
export type ListReposApiGithubReposGetQueryError = AxiosError<HTTPValidationError>


export function useListReposApiGithubReposGet<TData = Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError = AxiosError<HTTPValidationError>>(
 params: undefined |  ListReposApiGithubReposGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReposApiGithubReposGet>>,
          TError,
          Awaited<ReturnType<typeof listReposApiGithubReposGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReposApiGithubReposGet<TData = Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: ListReposApiGithubReposGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listReposApiGithubReposGet>>,
          TError,
          Awaited<ReturnType<typeof listReposApiGithubReposGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListReposApiGithubReposGet<TData = Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: ListReposApiGithubReposGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Repos
 */

export function useListReposApiGithubReposGet<TData = Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError = AxiosError<HTTPValidationError>>(
 params?: ListReposApiGithubReposGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listReposApiGithubReposGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListReposApiGithubReposGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get webhooks for a specific repository.
 * @summary Get Repo Webhooks
 */
export const getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet = (
    owner: string,
    repo: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GitHubWebhook[]>> => {
    
    
    return axios.default.get(
      `/api/github/repos/${owner}/${repo}/webhooks`,options
    );
  }




export const getGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGetQueryKey = (owner?: string,
    repo?: string,) => {
    return [
    `/api/github/repos/${owner}/${repo}/webhooks`
    ] as const;
    }

    
export const getGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGetQueryOptions = <TData = Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError = AxiosError<HTTPValidationError>>(owner: string,
    repo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGetQueryKey(owner,repo);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>> = ({ signal }) => getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet(owner,repo, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(owner && repo), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRepoWebhooksApiGithubReposOwnerRepoWebhooksGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>>
export type GetRepoWebhooksApiGithubReposOwnerRepoWebhooksGetQueryError = AxiosError<HTTPValidationError>


export function useGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGet<TData = Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError = AxiosError<HTTPValidationError>>(
 owner: string,
    repo: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>,
          TError,
          Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGet<TData = Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError = AxiosError<HTTPValidationError>>(
 owner: string,
    repo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>,
          TError,
          Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGet<TData = Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError = AxiosError<HTTPValidationError>>(
 owner: string,
    repo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Repo Webhooks
 */

export function useGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGet<TData = Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError = AxiosError<HTTPValidationError>>(
 owner: string,
    repo: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRepoWebhooksApiGithubReposOwnerRepoWebhooksGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRepoWebhooksApiGithubReposOwnerRepoWebhooksGetQueryOptions(owner,repo,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a webhook for commits on a repository.

Also creates a Project record to track the repo.
 * @summary Create Webhook
 */
export const createWebhookApiGithubReposOwnerRepoWebhooksPost = (
    owner: string,
    repo: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GitHubWebhook>> => {
    
    
    return axios.default.post(
      `/api/github/repos/${owner}/${repo}/webhooks`,undefined,options
    );
  }



export const getCreateWebhookApiGithubReposOwnerRepoWebhooksPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWebhookApiGithubReposOwnerRepoWebhooksPost>>, TError,{owner: string;repo: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createWebhookApiGithubReposOwnerRepoWebhooksPost>>, TError,{owner: string;repo: string}, TContext> => {

const mutationKey = ['createWebhookApiGithubReposOwnerRepoWebhooksPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWebhookApiGithubReposOwnerRepoWebhooksPost>>, {owner: string;repo: string}> = (props) => {
          const {owner,repo} = props ?? {};

          return  createWebhookApiGithubReposOwnerRepoWebhooksPost(owner,repo,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWebhookApiGithubReposOwnerRepoWebhooksPostMutationResult = NonNullable<Awaited<ReturnType<typeof createWebhookApiGithubReposOwnerRepoWebhooksPost>>>
    
    export type CreateWebhookApiGithubReposOwnerRepoWebhooksPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Webhook
 */
export const useCreateWebhookApiGithubReposOwnerRepoWebhooksPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWebhookApiGithubReposOwnerRepoWebhooksPost>>, TError,{owner: string;repo: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWebhookApiGithubReposOwnerRepoWebhooksPost>>,
        TError,
        {owner: string;repo: string},
        TContext
      > => {

      const mutationOptions = getCreateWebhookApiGithubReposOwnerRepoWebhooksPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a webhook from a repository.
 * @summary Delete Webhook
 */
export const deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete = (
    owner: string,
    repo: string,
    hookId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `/api/github/repos/${owner}/${repo}/webhooks/${hookId}`,options
    );
  }



export const getDeleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDeleteMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete>>, TError,{owner: string;repo: string;hookId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete>>, TError,{owner: string;repo: string;hookId: number}, TContext> => {

const mutationKey = ['deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete>>, {owner: string;repo: string;hookId: number}> = (props) => {
          const {owner,repo,hookId} = props ?? {};

          return  deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete(owner,repo,hookId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete>>>
    
    export type DeleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDeleteMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Webhook
 */
export const useDeleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete>>, TError,{owner: string;repo: string;hookId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDelete>>,
        TError,
        {owner: string;repo: string;hookId: number},
        TContext
      > => {

      const mutationOptions = getDeleteWebhookApiGithubReposOwnerRepoWebhooksHookIdDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Trigger a test ping for a webhook.
 * @summary Ping Webhook
 */
export const pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost = (
    owner: string,
    repo: string,
    hookId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/github/repos/${owner}/${repo}/webhooks/${hookId}/ping`,undefined,options
    );
  }



export const getPingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPostMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost>>, TError,{owner: string;repo: string;hookId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost>>, TError,{owner: string;repo: string;hookId: number}, TContext> => {

const mutationKey = ['pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost>>, {owner: string;repo: string;hookId: number}> = (props) => {
          const {owner,repo,hookId} = props ?? {};

          return  pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost(owner,repo,hookId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPostMutationResult = NonNullable<Awaited<ReturnType<typeof pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost>>>
    
    export type PingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPostMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Ping Webhook
 */
export const usePingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost>>, TError,{owner: string;repo: string;hookId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPost>>,
        TError,
        {owner: string;repo: string;hookId: number},
        TContext
      > => {

      const mutationOptions = getPingWebhookApiGithubReposOwnerRepoWebhooksHookIdPingPostMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    