services:
  api:
    build:
      context: ./
    env_file:
      - .env
      - docker-compose.env
    ports:
      - 8001:8000
    networks:
      - backend
    volumes:
      - go-mod-cache:/go/pkg/mod

  db_migrate:
    build:
      context: ./
    command:
      - "postgres://postgres:postgres@postgres:5432/july?sslmode=disable"
      - "up"
    env_file:
      - .env
      - docker-compose.env
    networks:
      - backend
    depends_on:
      db_create:
        condition: service_completed_successfully

  db_create:
    image: postgres:16-alpine
    environment:
      - PGPASSWORD=postgres
    command: >
      sh -c "psql -h postgres -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'july'\" | grep -q 1 || psql -h postgres -U postgres -c 'CREATE DATABASE july'"
    networks:
      - backend
    # depends_on:
    #   postgres:
    #     condition: service_healthy

  # postgres:
  #   container_name: postgres
  #   image: postgres:16-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - 5432:5432
  #   restart: always
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U postgres']
  #     start_period: 5s
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # adminer:
  #   container_name: adminer
  #   image: adminer:latest
  #   environment:
  #     - ADMINER_DESIGN=nette
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  smee:
    image: node:22-alpine
    command: ["npx", "smee-client", "-u", "${GITHUB_WEBHOOK_URL}", "-t", "http://api:8000/api/v1/github"]
    networks:
      - backend

volumes:
  go-mod-cache:

networks:
  backend:
    external: true
    name: backend