// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commits.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOrphanCommits = `-- name: ClaimOrphanCommits :execrows
UPDATE commits SET user_id = $1
WHERE user_id IS NULL
  AND email = ANY($2::text[])
  AND game_id = $3
`

type ClaimOrphanCommitsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Emails []string    `json:"emails"`
	GameID pgtype.UUID `json:"game_id"`
}

func (q *Queries) ClaimOrphanCommits(ctx context.Context, arg ClaimOrphanCommitsParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimOrphanCommits, arg.UserID, arg.Emails, arg.GameID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUserCommitsForGame = `-- name: CountUserCommitsForGame :one
SELECT
    COUNT(*)::int AS commit_count,
    COUNT(DISTINCT project_id)::int AS project_count
FROM commits
WHERE user_id = $1 AND game_id = $2
`

type CountUserCommitsForGameParams struct {
	UserID pgtype.UUID `json:"user_id"`
	GameID pgtype.UUID `json:"game_id"`
}

type CountUserCommitsForGameRow struct {
	CommitCount  int32 `json:"commit_count"`
	ProjectCount int32 `json:"project_count"`
}

func (q *Queries) CountUserCommitsForGame(ctx context.Context, arg CountUserCommitsForGameParams) (CountUserCommitsForGameRow, error) {
	row := q.db.QueryRow(ctx, countUserCommitsForGame, arg.UserID, arg.GameID)
	var i CountUserCommitsForGameRow
	err := row.Scan(&i.CommitCount, &i.ProjectCount)
	return i, err
}

const createCommit = `-- name: CreateCommit :one

INSERT INTO commits (id, hash, project_id, user_id, game_id, author, email, message, url, timestamp, languages, files)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (hash) DO NOTHING
RETURNING id, hash, project_id, user_id, game_id, author, email, message, url, timestamp, languages, files, is_verified, is_flagged, flag_reason, created_at, updated_at
`

type CreateCommitParams struct {
	ID        uuid.UUID   `json:"id"`
	Hash      pgtype.Text `json:"hash"`
	ProjectID uuid.UUID   `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	GameID    pgtype.UUID `json:"game_id"`
	Author    pgtype.Text `json:"author"`
	Email     pgtype.Text `json:"email"`
	Message   string      `json:"message"`
	Url       string      `json:"url"`
	Timestamp time.Time   `json:"timestamp"`
	Languages []string    `json:"languages"`
	Files     []byte      `json:"files"`
}

// ============================================
// Commits
// ============================================
func (q *Queries) CreateCommit(ctx context.Context, arg CreateCommitParams) (Commit, error) {
	row := q.db.QueryRow(ctx, createCommit,
		arg.ID,
		arg.Hash,
		arg.ProjectID,
		arg.UserID,
		arg.GameID,
		arg.Author,
		arg.Email,
		arg.Message,
		arg.Url,
		arg.Timestamp,
		arg.Languages,
		arg.Files,
	)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ProjectID,
		&i.UserID,
		&i.GameID,
		&i.Author,
		&i.Email,
		&i.Message,
		&i.Url,
		&i.Timestamp,
		&i.Languages,
		&i.Files,
		&i.IsVerified,
		&i.IsFlagged,
		&i.FlagReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const flagCommit = `-- name: FlagCommit :exec
UPDATE commits SET
    is_flagged = true,
    flag_reason = $1
WHERE id = $2
`

type FlagCommitParams struct {
	FlagReason pgtype.Text `json:"flag_reason"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) FlagCommit(ctx context.Context, arg FlagCommitParams) error {
	_, err := q.db.Exec(ctx, flagCommit, arg.FlagReason, arg.ID)
	return err
}

const getCommitByHash = `-- name: GetCommitByHash :one
SELECT id, hash, project_id, user_id, game_id, author, email, message, url, timestamp, languages, files, is_verified, is_flagged, flag_reason, created_at, updated_at FROM commits WHERE hash = $1
`

func (q *Queries) GetCommitByHash(ctx context.Context, hash pgtype.Text) (Commit, error) {
	row := q.db.QueryRow(ctx, getCommitByHash, hash)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ProjectID,
		&i.UserID,
		&i.GameID,
		&i.Author,
		&i.Email,
		&i.Message,
		&i.Url,
		&i.Timestamp,
		&i.Languages,
		&i.Files,
		&i.IsVerified,
		&i.IsFlagged,
		&i.FlagReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommitByID = `-- name: GetCommitByID :one
SELECT id, hash, project_id, user_id, game_id, author, email, message, url, timestamp, languages, files, is_verified, is_flagged, flag_reason, created_at, updated_at FROM commits WHERE id = $1
`

func (q *Queries) GetCommitByID(ctx context.Context, id uuid.UUID) (Commit, error) {
	row := q.db.QueryRow(ctx, getCommitByID, id)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ProjectID,
		&i.UserID,
		&i.GameID,
		&i.Author,
		&i.Email,
		&i.Message,
		&i.Url,
		&i.Timestamp,
		&i.Languages,
		&i.Files,
		&i.IsVerified,
		&i.IsFlagged,
		&i.FlagReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommitStats = `-- name: GetCommitStats :one
SELECT
    COUNT(*) AS total_commits,
    COUNT(DISTINCT user_id) FILTER (WHERE user_id IS NOT NULL) AS unique_users,
    COUNT(DISTINCT project_id) AS unique_projects
FROM commits
WHERE game_id = $1
`

type GetCommitStatsRow struct {
	TotalCommits   int64 `json:"total_commits"`
	UniqueUsers    int64 `json:"unique_users"`
	UniqueProjects int64 `json:"unique_projects"`
}

func (q *Queries) GetCommitStats(ctx context.Context, gameID pgtype.UUID) (GetCommitStatsRow, error) {
	row := q.db.QueryRow(ctx, getCommitStats, gameID)
	var i GetCommitStatsRow
	err := row.Scan(&i.TotalCommits, &i.UniqueUsers, &i.UniqueProjects)
	return i, err
}

const getCommitsByProject = `-- name: GetCommitsByProject :many
SELECT id, hash, project_id, user_id, game_id, author, email, message, url, timestamp, languages, files, is_verified, is_flagged, flag_reason, created_at, updated_at FROM commits
WHERE project_id = $1
ORDER BY id DESC
LIMIT GREATEST($3, 1) OFFSET $2
`

type GetCommitsByProjectParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  interface{} `json:"limit_count"`
}

func (q *Queries) GetCommitsByProject(ctx context.Context, arg GetCommitsByProjectParams) ([]Commit, error) {
	rows, err := q.db.Query(ctx, getCommitsByProject, arg.ProjectID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.ProjectID,
			&i.UserID,
			&i.GameID,
			&i.Author,
			&i.Email,
			&i.Message,
			&i.Url,
			&i.Timestamp,
			&i.Languages,
			&i.Files,
			&i.IsVerified,
			&i.IsFlagged,
			&i.FlagReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommitsByUserAndGame = `-- name: GetCommitsByUserAndGame :many
SELECT id, hash, project_id, user_id, game_id, author, email, message, url, timestamp, languages, files, is_verified, is_flagged, flag_reason, created_at, updated_at FROM commits
WHERE user_id = $1 AND game_id = $2
ORDER BY id DESC
LIMIT GREATEST($4, 1) OFFSET $3
`

type GetCommitsByUserAndGameParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	GameID      pgtype.UUID `json:"game_id"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  interface{} `json:"limit_count"`
}

func (q *Queries) GetCommitsByUserAndGame(ctx context.Context, arg GetCommitsByUserAndGameParams) ([]Commit, error) {
	rows, err := q.db.Query(ctx, getCommitsByUserAndGame,
		arg.UserID,
		arg.GameID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commit
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.ProjectID,
			&i.UserID,
			&i.GameID,
			&i.Author,
			&i.Email,
			&i.Message,
			&i.Url,
			&i.Timestamp,
			&i.Languages,
			&i.Files,
			&i.IsVerified,
			&i.IsFlagged,
			&i.FlagReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyCommitCounts = `-- name: GetDailyCommitCounts :many
SELECT
    DATE(timestamp) AS commit_date,
    COUNT(*)::int AS commit_count
FROM commits
WHERE game_id = $1
GROUP BY DATE(timestamp)
ORDER BY commit_date
`

type GetDailyCommitCountsRow struct {
	CommitDate  pgtype.Date `json:"commit_date"`
	CommitCount int32       `json:"commit_count"`
}

func (q *Queries) GetDailyCommitCounts(ctx context.Context, gameID pgtype.UUID) ([]GetDailyCommitCountsRow, error) {
	rows, err := q.db.Query(ctx, getDailyCommitCounts, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyCommitCountsRow
	for rows.Next() {
		var i GetDailyCommitCountsRow
		if err := rows.Scan(&i.CommitDate, &i.CommitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectGameActivityAggregates = `-- name: GetProjectGameActivityAggregates :one
SELECT
    COUNT(*)::int AS commits_this_month,
    COUNT(*) FILTER (WHERE c.timestamp >= $1)::int AS commits_this_week,
    COALESCE(SUM(
        CASE
            WHEN jsonb_typeof(c.files) = 'array' THEN jsonb_array_length(c.files)
            ELSE 0
        END
    ), 0)::int AS file_touch_count,
    (
        SELECT COUNT(DISTINCT dir_path)::int
        FROM (
            SELECT
                CASE
                    WHEN position('/' IN elem->>'file') = 0 THEN '.'
                    ELSE left(elem->>'file', length(elem->>'file') - length(elem->>'file') + position('/' IN reverse(elem->>'file')) - 1)
                END AS dir_path
            FROM commits c2
            CROSS JOIN LATERAL jsonb_array_elements(
                CASE WHEN jsonb_typeof(c2.files) = 'array' THEN c2.files ELSE '[]'::jsonb END
            ) AS elem
            WHERE c2.project_id = $2
              AND c2.game_id = $3
              AND c2.timestamp >= $4
              AND elem->>'file' IS NOT NULL
              AND elem->>'file' != ''
        ) paths
    ) AS unique_dirs
FROM commits c
WHERE c.project_id = $2
  AND c.game_id = $3
  AND c.timestamp >= $4
`

type GetProjectGameActivityAggregatesParams struct {
	WeekStart  time.Time   `json:"week_start"`
	ProjectID  uuid.UUID   `json:"project_id"`
	GameID     pgtype.UUID `json:"game_id"`
	MonthStart time.Time   `json:"month_start"`
}

type GetProjectGameActivityAggregatesRow struct {
	CommitsThisMonth int32 `json:"commits_this_month"`
	CommitsThisWeek  int32 `json:"commits_this_week"`
	FileTouchCount   int32 `json:"file_touch_count"`
	UniqueDirs       int32 `json:"unique_dirs"`
}

func (q *Queries) GetProjectGameActivityAggregates(ctx context.Context, arg GetProjectGameActivityAggregatesParams) (GetProjectGameActivityAggregatesRow, error) {
	row := q.db.QueryRow(ctx, getProjectGameActivityAggregates,
		arg.WeekStart,
		arg.ProjectID,
		arg.GameID,
		arg.MonthStart,
	)
	var i GetProjectGameActivityAggregatesRow
	err := row.Scan(
		&i.CommitsThisMonth,
		&i.CommitsThisWeek,
		&i.FileTouchCount,
		&i.UniqueDirs,
	)
	return i, err
}

const getRecentCommits = `-- name: GetRecentCommits :many
SELECT
    c.id,
    c.hash,
    c.message,
    c.timestamp,
    c.author,
    u.username,
    u.avatar_url,
    p.slug AS project_slug,
    p.name AS project_name
FROM commits c
LEFT JOIN users u ON u.id = c.user_id
JOIN projects p ON p.id = c.project_id
WHERE c.game_id = $1
ORDER BY c.timestamp DESC
LIMIT GREATEST($2, 1)
`

type GetRecentCommitsParams struct {
	GameID     pgtype.UUID `json:"game_id"`
	LimitCount interface{} `json:"limit_count"`
}

type GetRecentCommitsRow struct {
	ID          uuid.UUID   `json:"id"`
	Hash        pgtype.Text `json:"hash"`
	Message     string      `json:"message"`
	Timestamp   time.Time   `json:"timestamp"`
	Author      pgtype.Text `json:"author"`
	Username    pgtype.Text `json:"username"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	ProjectSlug string      `json:"project_slug"`
	ProjectName string      `json:"project_name"`
}

func (q *Queries) GetRecentCommits(ctx context.Context, arg GetRecentCommitsParams) ([]GetRecentCommitsRow, error) {
	rows, err := q.db.Query(ctx, getRecentCommits, arg.GameID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentCommitsRow
	for rows.Next() {
		var i GetRecentCommitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Message,
			&i.Timestamp,
			&i.Author,
			&i.Username,
			&i.AvatarUrl,
			&i.ProjectSlug,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnverifiedCommits = `-- name: GetUnverifiedCommits :many
SELECT c.id, c.hash, c.project_id, c.user_id, c.game_id, c.author, c.email, c.message, c.url, c.timestamp, c.languages, c.files, c.is_verified, c.is_flagged, c.flag_reason, c.created_at, c.updated_at, p.url AS project_url, p.name AS project_name
FROM commits c
JOIN projects p ON p.id = c.project_id
WHERE c.is_verified = false AND c.is_flagged = false
ORDER BY c.created_at ASC
LIMIT GREATEST($1, 1)
`

type GetUnverifiedCommitsRow struct {
	ID          uuid.UUID   `json:"id"`
	Hash        pgtype.Text `json:"hash"`
	ProjectID   uuid.UUID   `json:"project_id"`
	UserID      pgtype.UUID `json:"user_id"`
	GameID      pgtype.UUID `json:"game_id"`
	Author      pgtype.Text `json:"author"`
	Email       pgtype.Text `json:"email"`
	Message     string      `json:"message"`
	Url         string      `json:"url"`
	Timestamp   time.Time   `json:"timestamp"`
	Languages   []string    `json:"languages"`
	Files       []byte      `json:"files"`
	IsVerified  bool        `json:"is_verified"`
	IsFlagged   bool        `json:"is_flagged"`
	FlagReason  pgtype.Text `json:"flag_reason"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	ProjectUrl  string      `json:"project_url"`
	ProjectName string      `json:"project_name"`
}

func (q *Queries) GetUnverifiedCommits(ctx context.Context, limitCount interface{}) ([]GetUnverifiedCommitsRow, error) {
	rows, err := q.db.Query(ctx, getUnverifiedCommits, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnverifiedCommitsRow
	for rows.Next() {
		var i GetUnverifiedCommitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.ProjectID,
			&i.UserID,
			&i.GameID,
			&i.Author,
			&i.Email,
			&i.Message,
			&i.Url,
			&i.Timestamp,
			&i.Languages,
			&i.Files,
			&i.IsVerified,
			&i.IsFlagged,
			&i.FlagReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectUrl,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommitGame = `-- name: SetCommitGame :exec
UPDATE commits
SET game_id = $1
WHERE id = $2
`

type SetCommitGameParams struct {
	GameID pgtype.UUID `json:"game_id"`
	ID     uuid.UUID   `json:"id"`
}

func (q *Queries) SetCommitGame(ctx context.Context, arg SetCommitGameParams) error {
	_, err := q.db.Exec(ctx, setCommitGame, arg.GameID, arg.ID)
	return err
}

const verifyCommit = `-- name: VerifyCommit :exec
UPDATE commits SET is_verified = true WHERE id = $1
`

func (q *Queries) VerifyCommit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyCommit, id)
	return err
}
