// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          uuid.UUID   `json:"id"`
	ModeratorID uuid.UUID   `json:"moderator_id"`
	Action      string      `json:"action"`
	TargetType  string      `json:"target_type"`
	TargetID    string      `json:"target_id"`
	Reason      pgtype.Text `json:"reason"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Board struct {
	ID               uuid.UUID `json:"id"`
	GameID           uuid.UUID `json:"game_id"`
	ProjectID        uuid.UUID `json:"project_id"`
	Points           int32     `json:"points"`
	PotentialPoints  int32     `json:"potential_points"`
	VerifiedPoints   int32     `json:"verified_points"`
	CommitCount      int32     `json:"commit_count"`
	ContributorCount int32     `json:"contributor_count"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Commit struct {
	ID         uuid.UUID   `json:"id"`
	Hash       pgtype.Text `json:"hash"`
	ProjectID  uuid.UUID   `json:"project_id"`
	UserID     pgtype.UUID `json:"user_id"`
	GameID     pgtype.UUID `json:"game_id"`
	Author     pgtype.Text `json:"author"`
	Email      pgtype.Text `json:"email"`
	Message    string      `json:"message"`
	Url        string      `json:"url"`
	Timestamp  time.Time   `json:"timestamp"`
	Languages  []string    `json:"languages"`
	Files      []byte      `json:"files"`
	IsVerified bool        `json:"is_verified"`
	IsFlagged  bool        `json:"is_flagged"`
	FlagReason pgtype.Text `json:"flag_reason"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type Game struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	StartsAt      time.Time `json:"starts_at"`
	EndsAt        time.Time `json:"ends_at"`
	CommitPoints  int32     `json:"commit_points"`
	ProjectPoints int32     `json:"project_points"`
	IsActive      bool      `json:"is_active"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Language struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type LanguageBoard struct {
	ID          uuid.UUID `json:"id"`
	GameID      uuid.UUID `json:"game_id"`
	LanguageID  uuid.UUID `json:"language_id"`
	Points      int32     `json:"points"`
	CommitCount int32     `json:"commit_count"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Player struct {
	ID              uuid.UUID          `json:"id"`
	GameID          uuid.UUID          `json:"game_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Points          int32              `json:"points"`
	PotentialPoints int32              `json:"potential_points"`
	VerifiedPoints  int32              `json:"verified_points"`
	CommitCount     int32              `json:"commit_count"`
	ProjectCount    int32              `json:"project_count"`
	AnalysisStatus  string             `json:"analysis_status"`
	LastAnalyzedAt  pgtype.Timestamptz `json:"last_analyzed_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type Project struct {
	ID          uuid.UUID   `json:"id"`
	Url         string      `json:"url"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	RepoID      pgtype.Int8 `json:"repo_id"`
	Service     string      `json:"service"`
	Forked      bool        `json:"forked"`
	Forks       int32       `json:"forks"`
	Watchers    int32       `json:"watchers"`
	ParentUrl   pgtype.Text `json:"parent_url"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Report struct {
	ID             uuid.UUID          `json:"id"`
	ReportedUserID pgtype.UUID        `json:"reported_user_id"`
	ReportType     string             `json:"report_type"`
	Reason         pgtype.Text        `json:"reason"`
	Status         string             `json:"status"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	ModeratorNotes pgtype.Text        `json:"moderator_notes"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type Team struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	IsPublic    bool        `json:"is_public"`
	MemberCount int32       `json:"member_count"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type TeamBoard struct {
	ID          uuid.UUID `json:"id"`
	GameID      uuid.UUID `json:"game_id"`
	TeamID      uuid.UUID `json:"team_id"`
	Points      int32     `json:"points"`
	MemberCount int32     `json:"member_count"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type TeamMember struct {
	ID        uuid.UUID `json:"id"`
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Username     string             `json:"username"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	IsBanned     bool               `json:"is_banned"`
	BannedReason pgtype.Text        `json:"banned_reason"`
	BannedAt     pgtype.Timestamptz `json:"banned_at"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type UserIdentifier struct {
	Value     string    `json:"value"`
	Type      string    `json:"type"`
	UserID    uuid.UUID `json:"user_id"`
	Verified  bool      `json:"verified"`
	IsPrimary bool      `json:"is_primary"`
	Data      []byte    `json:"data"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
