// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (id, team_id, user_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT uq_team_member DO UPDATE SET role = EXCLUDED.role
RETURNING id, team_id, user_id, role, created_at, updated_at
`

type AddTeamMemberParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember,
		arg.ID,
		arg.TeamID,
		arg.UserID,
		arg.Role,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one

INSERT INTO teams (id, name, slug, description, avatar_url, created_by, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, slug, description, avatar_url, created_by, is_public, member_count, created_at, updated_at
`

type CreateTeamParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	IsPublic    bool        `json:"is_public"`
}

// ============================================
// Teams
// ============================================
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.AvatarUrl,
		arg.CreatedBy,
		arg.IsPublic,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatedBy,
		&i.IsPublic,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, slug, description, avatar_url, created_by, is_public, member_count, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatedBy,
		&i.IsPublic,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, name, slug, description, avatar_url, created_by, is_public, member_count, created_at, updated_at FROM teams WHERE slug = $1
`

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatedBy,
		&i.IsPublic,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamLeaderboard = `-- name: GetTeamLeaderboard :many
SELECT tb.id, tb.game_id, tb.team_id, tb.points, tb.member_count, tb.created_at, tb.updated_at, t.name AS team_name, t.slug, t.avatar_url
FROM team_boards tb
JOIN teams t ON t.id = tb.team_id
WHERE tb.game_id = $1
ORDER BY tb.points DESC
LIMIT $2
`

type GetTeamLeaderboardParams struct {
	GameID     uuid.UUID `json:"game_id"`
	LimitCount int32     `json:"limit_count"`
}

type GetTeamLeaderboardRow struct {
	ID          uuid.UUID   `json:"id"`
	GameID      uuid.UUID   `json:"game_id"`
	TeamID      uuid.UUID   `json:"team_id"`
	Points      int32       `json:"points"`
	MemberCount int32       `json:"member_count"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	TeamName    string      `json:"team_name"`
	Slug        string      `json:"slug"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) GetTeamLeaderboard(ctx context.Context, arg GetTeamLeaderboardParams) ([]GetTeamLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getTeamLeaderboard, arg.GameID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamLeaderboardRow
	for rows.Next() {
		var i GetTeamLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.TeamID,
			&i.Points,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamName,
			&i.Slug,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, team_id, user_id, role, created_at, updated_at FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicTeams = `-- name: ListPublicTeams :many
SELECT id, name, slug, description, avatar_url, created_by, is_public, member_count, created_at, updated_at FROM teams
WHERE is_public = true
ORDER BY member_count DESC, created_at DESC
LIMIT $2 OFFSET $1
`

type ListPublicTeamsParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListPublicTeams(ctx context.Context, arg ListPublicTeamsParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listPublicTeams, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.AvatarUrl,
			&i.CreatedBy,
			&i.IsPublic,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id, tm.team_id, tm.user_id, tm.role, tm.created_at, tm.updated_at, u.name, u.username, u.avatar_url
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY tm.role DESC, tm.created_at
`

type ListTeamMembersRow struct {
	ID        uuid.UUID   `json:"id"`
	TeamID    uuid.UUID   `json:"team_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      string      `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Name      string      `json:"name"`
	Username  string      `json:"username"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.name, t.slug, t.description, t.avatar_url, t.created_by, t.is_public, t.member_count, t.created_at, t.updated_at, tm.role AS member_role
FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = $1
ORDER BY t.name
`

type ListUserTeamsRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	IsPublic    bool        `json:"is_public"`
	MemberCount int32       `json:"member_count"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	MemberRole  string      `json:"member_role"`
}

func (q *Queries) ListUserTeams(ctx context.Context, userID uuid.UUID) ([]ListUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserTeamsRow
	for rows.Next() {
		var i ListUserTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.AvatarUrl,
			&i.CreatedBy,
			&i.IsPublic,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    avatar_url = COALESCE($3, avatar_url),
    is_public = COALESCE($4, is_public)
WHERE id = $5
`

type UpdateTeamParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	IsPublic    pgtype.Bool `json:"is_public"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.Exec(ctx, updateTeam,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.IsPublic,
		arg.ID,
	)
	return err
}

const updateTeamMemberCount = `-- name: UpdateTeamMemberCount :exec
UPDATE teams SET member_count = (
    SELECT COUNT(*) FROM team_members WHERE team_id = $1
) WHERE id = $1
`

func (q *Queries) UpdateTeamMemberCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateTeamMemberCount, id)
	return err
}

const upsertTeamBoard = `-- name: UpsertTeamBoard :one
INSERT INTO team_boards (id, game_id, team_id, points, member_count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT uq_team_board
DO UPDATE SET
    points = EXCLUDED.points,
    member_count = EXCLUDED.member_count
RETURNING id, game_id, team_id, points, member_count, created_at, updated_at
`

type UpsertTeamBoardParams struct {
	ID          uuid.UUID `json:"id"`
	GameID      uuid.UUID `json:"game_id"`
	TeamID      uuid.UUID `json:"team_id"`
	Points      int32     `json:"points"`
	MemberCount int32     `json:"member_count"`
}

func (q *Queries) UpsertTeamBoard(ctx context.Context, arg UpsertTeamBoardParams) (TeamBoard, error) {
	row := q.db.QueryRow(ctx, upsertTeamBoard,
		arg.ID,
		arg.GameID,
		arg.TeamID,
		arg.Points,
		arg.MemberCount,
	)
	var i TeamBoard
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.TeamID,
		&i.Points,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
