"""
add is_active index

Revision ID: 3731f6406b77
Revises: c88c9ed18482
Create Date: 2025-12-29 13:54:00.523229

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision = "3731f6406b77"
down_revision = "c88c9ed18482"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_project_is_active"), "project", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_user_is_active"), "user", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_is_active"), table_name="user")
    op.drop_index(op.f("ix_project_is_active"), table_name="project")
    # ### end Alembic commands ###
