"""
username unique

Revision ID: d107384ad60b
Revises: f58822b42896
Create Date: 2026-01-01 08:43:51.705659

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision = "d107384ad60b"
down_revision = "f58822b42896"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=25), nullable=False
    )
    op.create_unique_constraint("unique-user-username", "user", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique-user-username", "user", type_="unique")
    op.alter_column(
        "user", "username", existing_type=sa.VARCHAR(length=25), nullable=True
    )
    # ### end Alembic commands ###
