"""
add_unique_constraints

Revision ID: 76f88c250081
Revises: d107384ad60b
Create Date: 2026-01-01 17:58:30.340574

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision = '76f88c250081'
down_revision = 'd107384ad60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_board_project_game', 'board', ['game_id', 'project_id'])
    op.create_unique_constraint('uq_language_game', 'languageboard', ['game_id', 'language_id'])
    op.create_unique_constraint('uq_player_user_game', 'player', ['game_id', 'user_id'])
    op.create_unique_constraint('uq_teamboard_team_game', 'teamboard', ['game_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teamboard_team_game', 'teamboard', type_='unique')
    op.drop_constraint('uq_player_user_game', 'player', type_='unique')
    op.drop_constraint('uq_language_game', 'languageboard', type_='unique')
    op.drop_constraint('uq_board_project_game', 'board', type_='unique')
    # ### end Alembic commands ###