/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Julython API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';





/**
 * @summary Health
 */
export const healthApiConfigGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.get(
      `/api/config`,options
    );
  }




export const getHealthApiConfigGetQueryKey = () => {
    return [
    `/api/config`
    ] as const;
    }

    
export const getHealthApiConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof healthApiConfigGet>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiConfigGet>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthApiConfigGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthApiConfigGet>>> = ({ signal }) => healthApiConfigGet({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthApiConfigGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthApiConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthApiConfigGet>>>
export type HealthApiConfigGetQueryError = AxiosError<unknown>


export function useHealthApiConfigGet<TData = Awaited<ReturnType<typeof healthApiConfigGet>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiConfigGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiConfigGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiConfigGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiConfigGet<TData = Awaited<ReturnType<typeof healthApiConfigGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiConfigGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthApiConfigGet>>,
          TError,
          Awaited<ReturnType<typeof healthApiConfigGet>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthApiConfigGet<TData = Awaited<ReturnType<typeof healthApiConfigGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiConfigGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthApiConfigGet<TData = Awaited<ReturnType<typeof healthApiConfigGet>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthApiConfigGet>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthApiConfigGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




