// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one

INSERT INTO reports (id, reported_user_id, report_type, reason, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, reported_user_id, report_type, reason, status, reviewed_by, reviewed_at, moderator_notes, created_at, updated_at
`

type CreateReportParams struct {
	ID             uuid.UUID   `json:"id"`
	ReportedUserID pgtype.UUID `json:"reported_user_id"`
	ReportType     string      `json:"report_type"`
	Reason         pgtype.Text `json:"reason"`
}

// ============================================
// Reports
// ============================================
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReportedUserID,
		arg.ReportType,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportedUserID,
		&i.ReportType,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ModeratorNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, reported_user_id, report_type, reason, status, reviewed_by, reviewed_at, moderator_notes, created_at, updated_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportedUserID,
		&i.ReportType,
		&i.Reason,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ModeratorNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingReports = `-- name: ListPendingReports :many
SELECT r.id, r.reported_user_id, r.report_type, r.reason, r.status, r.reviewed_by, r.reviewed_at, r.moderator_notes, r.created_at, r.updated_at, u.username AS reported_username
FROM reports r
LEFT JOIN users u ON u.id = r.reported_user_id
WHERE r.status = 'pending'
ORDER BY r.created_at ASC
LIMIT $1
`

type ListPendingReportsRow struct {
	ID               uuid.UUID          `json:"id"`
	ReportedUserID   pgtype.UUID        `json:"reported_user_id"`
	ReportType       string             `json:"report_type"`
	Reason           pgtype.Text        `json:"reason"`
	Status           string             `json:"status"`
	ReviewedBy       pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	ModeratorNotes   pgtype.Text        `json:"moderator_notes"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ReportedUsername pgtype.Text        `json:"reported_username"`
}

func (q *Queries) ListPendingReports(ctx context.Context, limitCount int32) ([]ListPendingReportsRow, error) {
	rows, err := q.db.Query(ctx, listPendingReports, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingReportsRow
	for rows.Next() {
		var i ListPendingReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportedUserID,
			&i.ReportType,
			&i.Reason,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ModeratorNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReportedUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewReport = `-- name: ReviewReport :exec
UPDATE reports SET
    status = $1,
    reviewed_by = $2,
    reviewed_at = now(),
    moderator_notes = $3
WHERE id = $4
`

type ReviewReportParams struct {
	Status         string      `json:"status"`
	ReviewedBy     pgtype.UUID `json:"reviewed_by"`
	ModeratorNotes pgtype.Text `json:"moderator_notes"`
	ID             uuid.UUID   `json:"id"`
}

func (q *Queries) ReviewReport(ctx context.Context, arg ReviewReportParams) error {
	_, err := q.db.Exec(ctx, reviewReport,
		arg.Status,
		arg.ReviewedBy,
		arg.ModeratorNotes,
		arg.ID,
	)
	return err
}
